// Generated by CoffeeScript 1.3.1
(function() {

  Template.box.message = function() {
    var message;
    if (message = Messages.findOne({
      permalink: "sample-box"
    })) {
      return message.text;
    }
  };

  Template.box.events = {
    'keyup textarea': function(e) {
      var typedText;
      typedText = $(e.srcElement).val();
      return Messages.update({
        permalink: "sample-box"
      }, {
        $set: {
          text: typedText
        }
      });
    }
  };

}).call(this);
