// Generated by CoffeeScript 1.3.1
(function() {
  var globalObject;

  globalObject = Meteor.is_client ? window : global;

  globalObject.Messages = new Meteor.Collection("messages");

}).call(this);
